### ISSUE TITLE
'NoneType' object has no attribute 'info'

### ISSUE THREAD

**Issue by geroldhinzen** [Skoda091/alfred-deepl#10]
<img width="289" alt="bildschirmfoto 2018-08-06 um 19 30 36" src="https://user-images.githubusercontent.com/4331332/43731583-3acb806e-99af-11e8-9253-4ca57a17c602.png">

[2018-08-06 19:31:06][ERROR: input.scriptfilter] Code 1: 19:31:05 workflow.py:2247 DEBUG    ---------- DeepL (1.1.0) ----------
19:31:05 workflow.py:1657 DEBUG    reading settings from /Users/XXX/Library/Application Support/Alfred 3/Workflow Data/com.skoda091.deepl-translation/settings.json
19:31:05 workflow.py:2531 DEBUG    update check not due
19:31:05 workflow.py:1884 DEBUG    loading cached data: /Users/XXX/Library/Caches/com.runningwithcrayons.Alfred-3/Workflow Data/com.skoda091.deepl-translation/__workflow_update_status.cpickle
19:31:05 workflow.py:2461 DEBUG    update_data: {u'available': False}
19:31:06 workflow.py:2266 ERROR    'NoneType' object has no attribute 'info'
Traceback (most recent call last):
  File "/Users/XXX/XXX/alfred-sync/Alfred.alfredpreferences/workflows/user.workflow.130FF627-ADC7-4587-A7E0-F337A48601D3/workflow/workflow.py", line 2259, in run
    func(self)
  File "deepl.py", line 101, in main
    translations = json.loads(response.text)['result']['translations']
  File "/Users/XXX/XXX/alfred-sync/Alfred.alfredpreferences/workflows/user.workflow.130FF627-ADC7-4587-A7E0-F337A48601D3/workflow/web.py", line 319, in text
    if self.encoding:
  File "/Users/XXX/XXX/alfred-sync/Alfred.alfredpreferences/workflows/user.workflow.130FF627-ADC7-4587-A7E0-F337A48601D3/workflow/web.py", line 282, in encoding
    self._encoding = self._get_encoding()
  File "/Users/XXX/XXX/alfred-sync/Alfred.alfredpreferences/workflows/user.workflow.130FF627-ADC7-4587-A7E0-F337A48601D3/workflow/web.py", line 415, in _get_encoding
    headers = self.raw.info()
AttributeError: 'NoneType' object has no attribute 'info'
19:31:06 workflow.py:2268 INFO     for assistance, see: https://github.com/Skoda091/alfred-deepl
19:31:06 workflow.py:2289 DEBUG    ---------- finished in 0.239s ----------
[2018-08-06 19:31:06][ERROR: input.scriptfilter] Code 1: 19:31:06 workflow.py:2247 DEBUG    ---------- DeepL (1.1.0) ----------
19:31:06 workflow.py:1657 DEBUG    reading settings from /Users/XXX/Library/Application Support/Alfred 3/Workflow Data/com.skoda091.deepl-translation/settings.json
19:31:06 workflow.py:2531 DEBUG    update check not due
19:31:06 workflow.py:1884 DEBUG    loading cached data: /Users/XXX/Library/Caches/com.runningwithcrayons.Alfred-3/Workflow Data/com.skoda091.deepl-translation/__workflow_update_status.cpickle
19:31:06 workflow.py:2461 DEBUG    update_data: {u'available': False}
19:31:06 workflow.py:2266 ERROR    'NoneType' object has no attribute 'info'
Traceback (most recent call last):
  File "/Users/XXX/XXX/alfred-sync/Alfred.alfredpreferences/workflows/user.workflow.130FF627-ADC7-4587-A7E0-F337A48601D3/workflow/workflow.py", line 2259, in run
    func(self)
  File "deepl.py", line 101, in main
    translations = json.loads(response.text)['result']['translations']
  File "/Users/XXX/XXX/alfred-sync/Alfred.alfredpreferences/workflows/user.workflow.130FF627-ADC7-4587-A7E0-F337A48601D3/workflow/web.py", line 319, in text
    if self.encoding:
  File "/Users/XXX/XXX/alfred-sync/Alfred.alfredpreferences/workflows/user.workflow.130FF627-ADC7-4587-A7E0-F337A48601D3/workflow/web.py", line 282, in encoding
    self._encoding = self._get_encoding()
  File "/Users/XXX/XXX/alfred-sync/Alfred.alfredpreferences/workflows/user.workflow.130FF627-ADC7-4587-A7E0-F337A48601D3/workflow/web.py", line 415, in _get_encoding
    headers = self.raw.info()
AttributeError: 'NoneType' object has no attribute 'info'
19:31:06 workflow.py:2268 INFO     for assistance, see: https://github.com/Skoda091/alfred-deepl
19:31:06 workflow.py:2289 DEBUG    ---------- finished in 0.256s ----------

**Comment by holymio** [comment]
Have the same problem.

**Comment by sutefan1** [comment]
Same here
```
Starting debug for 'DeepL'

[2019-01-11 13:56:08][ERROR: input.scriptfilter] Code 1: 13:56:08 workflow.py:2247 DEBUG    ---------- DeepL (1.1.0) ----------
13:56:08 workflow.py:1657 DEBUG    reading settings from /Users/stefan/Library/Application Support/Alfred 3/Workflow Data/com.skoda091.deepl-translation/settings.json
13:56:08 workflow.py:2531 DEBUG    update check not due
13:56:08 workflow.py:1884 DEBUG    loading cached data: /Users/stefan/Library/Caches/com.runningwithcrayons.Alfred-3/Workflow Data/com.skoda091.deepl-translation/__workflow_update_status.cpickle
13:56:08 workflow.py:2461 DEBUG    update_data: {u'available': False}
13:56:08 workflow.py:2266 ERROR    'NoneType' object has no attribute 'info'
Traceback (most recent call last):
  File "/Users/stefan/Library/Application Support/Alfred 3/Alfred.alfredpreferences/workflows/user.workflow.1AB2C1B6-D980-4B90-93A5-9C7557BE6A18/workflow/workflow.py", line 2259, in run
    func(self)
  File "deepl.py", line 101, in main
    translations = json.loads(response.text)['result']['translations']
  File "/Users/stefan/Library/Application Support/Alfred 3/Alfred.alfredpreferences/workflows/user.workflow.1AB2C1B6-D980-4B90-93A5-9C7557BE6A18/workflow/web.py", line 319, in text
    if self.encoding:
  File "/Users/stefan/Library/Application Support/Alfred 3/Alfred.alfredpreferences/workflows/user.workflow.1AB2C1B6-D980-4B90-93A5-9C7557BE6A18/workflow/web.py", line 282, in encoding
    self._encoding = self._get_encoding()
  File "/Users/stefan/Library/Application Support/Alfred 3/Alfred.alfredpreferences/workflows/user.workflow.1AB2C1B6-D980-4B90-93A5-9C7557BE6A18/workflow/web.py", line 415, in _get_encoding
    headers = self.raw.info()
AttributeError: 'NoneType' object has no attribute 'info'
13:56:08 workflow.py:2268 INFO     for assistance, see: https://github.com/Skoda091/alfred-deepl
13:56:08 workflow.py:2289 DEBUG    ---------- finished in 0.306s ----------
```

**Comment by marcocastellani** [comment]
same here

**Comment by Ruko2010** [comment]
have somebody solved this Problem?

**Comment by datenreisender** [comment]
I assume this is caused by the fact that DeepL only allows authenticated requests to their API and this workflow does not authenticate you. Solving this probably would require getting a paid access to the API and then using a (different?) workflow which does allow you to authenticate yourself.
